# Site settings
title: Турагенство Авиатур Екатеринбург
email: avia@aviatour-ekb.ru
baseurl: http://aviatour.github.io/
url: http://aviatour.github.io/

# Build settings
markdown: rdiscount
permalink: pretty

stylus:
  compress: true
  path: ./styles

prose:
  rooturl: '_posts'
  siteurl: 'http://aviatour.github.io/'
  relativeLinks: 'http://aviatour.github.io/links.jsonp'
  media: 'media'
  ignore:
    - .gitignore
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_plugins
    - /_site
    - /images
    - /scripts
    - /styles
  metadata:
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Заголовок"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Постоянная ссылка"
          value: ""
    _posts/news:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "category"
        field:
          element: "hidden"
          value: "news"
      - name: "title"
        field:
          element: "text"
          label: "Заголовок"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Постоянная ссылка"
          value: ""