# Site settings
title: Турагенство Авиатур Екатеринбург
email: avia@aviatour-ekb.ru
baseurl: http://aviatour.github.io/
url: http://aviatour.github.io/

# Build settings
markdown: rdiscount
permalink: pretty

stylus:
  compress: true
  path: ./styles

prose:
  rooturl: './'
  siteurl: 'http://aviatour.github.io/'
  relativeLinks: 'http://aviatour.github.io/links.jsonp'
  media: 'media'